runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install Yarn Switch
      shell: bash
      run: |
        bash install-script.sh
